kind: ConfigMap
apiVersion: v1
metadata:
  name: monitoring-prometheus-alertmanager
  namespace: kube-system
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 5m

    templates:
    - '/etc/alertmanager-templates/*.tmpl'

    route:
      group_by: ['alertname', 'severity', 'receiver']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: sk-cps-ops 

    receivers:
    - name: 'default'
    - name: 'sk-cps-ops'
      slack_configs:
      - api_url: https://hooks.slack.com/services/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 
        send_resolved: true
    
